### ISSUE TITLE
Frontend Clean Architecture + Nice coding

### ISSUE THREAD

**Issue by mugengliu** [CSC207-2022F-UofT/course-project-dating-app-team#31]
It is also necessary to maintain a clean code for the front end. 
Here are the several steps:
1. Separate the js coding from HTML into js files. 
2. Separate the CSS coding from HTML into CSS files.
3. Give the variables and HTML elements better names
4. Add comment to each js and CSS file
5. Delete the frontend test code, such as the console.log(), alert()
To maintain the Architecture, these steps are necessary:
1. We are now using the MVVM model framework for the front end, the view shouldn't have many interactions with the input data. 
    This means we need to fix all the methods or functions that directly change the HTML elements.
2. Any useless function needs to be deleted. 
3. It is suggested that we add some entities to the front end. Although not necessary, may enhance the clean architecture.

**Comment by mugengliu** [comment]
I improved the code as I was concerned. Here is what I am thinking about the front-end architecture.
First, class is mandatory in the front end only if the developer chooses to use some lightweight framework such as jQuery or basic JS. 
Since now I haven't completely converted the whole coding under Vue, some still use jQuery, so I create three classes. 
But I find it is helpless cause Vue can do more work. What I am doing is just making the code easy to understand, but still that amount. So I will try to improve the event controller cause there are so many buttons right now. I plan to realize all of them by Vue instead of jQuery.

**Comment by roxanehe** [comment]
I can do the cleanup work for html css and Js, I ll start tomorrow when I have breaks during lunch time.
But I am not sure what are considered entities in front-end? are there some examples?

**Comment by mugengliu** [comment]
This is solved, create four classes for the frontend + MVVM model using Vue framework
