### ISSUE TITLE
chatting-individual

### ISSUE THREAD

**Issue by MikeJiahaoXu** [CSC207-2022F-UofT/course-project-dating-app-team#5]
This implements that chatting function

**Comment by mugengliu** [comment]
http://8.210.136.109/#

**Comment by mugengliu** [comment]
### Technology needs to be realized to ensure basic communication:
1. Web environment construction: In progress, the environment is settled 
2. Frontend-Backend-Database interaction: In progress, realize simple interaction, needs to fulfill the complex function
3. Full-duplex communication based on TCP/IP: **Not started**yet, need knowledge based on the web communication
4. Cookie data storage: **Not started yet**. 
Extremely important!!!!!!!
### Some work needs to be done before the deadline:
1. Webpage enhancement: jQuery + React + Vue
2. Frontend simplification: Reduce the redundant function, and give it to the backend
3. Expand the domain: Improve the frontend functionality
### Some other works could be done on frontend:
1. Improve the user experience on the webpage
   Visual: AE digital visual effects, 2D Live + 3D graphics
   Personalized pushing service: Email + Text message

**Comment by mugengliu** [comment]
### Current Web address (main page): 
http://k125.love:8080/k125
A further update will be noticed
Need to mirror the IP address, and change the port.

**Comment by mugengliu** [comment]
收藏前端特效个人网站: canvas + jquery
https://www.tianlunvip.com/sitemap.html

**Comment by mugengliu** [comment]
This is no more a requirement as we aim to design a blog instead of person-to-person chatting now.
